version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres
  web:
    build: .
    image: lambda_gp_trader_web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_LOG_TO_STDOUT=1
    volumes:
      - .:/lambdaGPTrader
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
